---
version: '3'

services:
  jenkins:
    build:
      context: ./build
    restart: unless-stopped
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jcasc
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - ./workspace:/var/jenkins_home
      - ./jcasc:/var/jenkins_home/jcasc
    ports:
      - 8080:8080
      - 50000:50000

