jenkins:
  numExecutors: 1
  authorizationStrategy:
    globalMatrix:
      entries:
      - user:
          name: "anonymous"
          permissions:
          - "Overall/Administer"

unclassified:
  location:
    url: "http://localhost:8080/"

jobs:
  - script: |
      pipelineJob('test') {
        quietPeriod(0)
        definition {
          cps {
            script """
              node('built-in') {
                  stage('Print env') {
                      sh 'env'
                  }
              }
            """
            sandbox()
          }
        }
      }
      queue('test')
